# This workflows will upload a Crate using cargo when a release is created

name: Upload Cargo Crate

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        CARGO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: |
        cargo publish --token ${CARGO_TOKEN} --manifest-path .\server\Cargo.toml
        cargo publish --token ${CARGO_TOKEN} --manifest-path .\rust_client\Cargo.toml

